# Generated by Django 4.1.5 on 2023-02-13 23:58

from django.db import migrations
from django.utils.translation import gettext_lazy as _


def add_youtube_service(apps, schema_editor):
    from embeds.models import Service as ServiceConst
    Service = apps.get_model("embeds", "Service")

    embed_template = (
        '<iframe id="ytplayer" type="text/html" width="720" height="405" '
        'src="https://www.youtube.com/embed/{media_id}" frameborder="0" allowfullscreen>'
    )

    uri_template = "https://youtu.be/{media_id}"

    Service.objects.create(
        id=ServiceConst.YOUTUBE,
        name=_("YouTube"),
        embed_template=embed_template,
        uri_template=uri_template,
    )


def remove_youtube_service(apps, schema_editor):
    from embeds.models import Service as ServiceConst
    Media = apps.get_model("embeds", "Media")
    Media.objects.filter(service_id=ServiceConst.YOUTUBE).delete()
    Service = apps.get_model("embeds", "Service")
    Service.objects.get(id=ServiceConst.YOUTUBE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("embeds", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_youtube_service, remove_youtube_service),
    ]
