# Generated by Django 4.1.7 on 2023-02-27 03:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("embeds", "0002_add_youtube_service"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="media",
            options={"verbose_name_plural": "Media"},
        ),
    ]
