---
- name: Ensure celery beat config directory exists
  ansible.builtin.file:
    path: "{{ celery_beat_config_dir }}"
    state: directory
    mode: '0755'
  become: yes

- name: Install celery beat env file
  ansible.builtin.template:
    src: templates/celery_beat_env.j2
    dest: "{{ celery_beat_config_path }}"
    owner: root
    group: www-data
    mode: '0640'
  become: yes
  notify: "restart celery beat"

- name: Install celery beat systemd service config
  ansible.builtin.template:
    src: templates/systemd_celery_beat.j2
    dest: "{{ systemd_config_dir }}/{{ celery_beat_service_name }}.service"
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: "restart celery beat"

- name: Enable and start celery beat
  ansible.builtin.systemd:
    name: "{{ celery_beat_service_name }}.service"
    enabled: yes
    state: started
    daemon_reload: yes
  become: yes
...
