version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    assignees:
      - "Apreche"
    target-branch: "main"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      production-updates:
        applies-to: version-updates
        update-types:
        - "minor"
        - "patch"
      security-updates:
        applies-to: security-updates
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: "npm"
    directory: "/"
    assignees:
      - "Apreche"
    target-branch: "main"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      production-updates:
        applies-to: version-updates
        update-types:
        - "minor"
        - "patch"
      security-updates:
        applies-to: security-updates
        update-types:
        - "minor"
        - "patch"
