version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    assignees:
      - "Apreche"
    target-branch: "main"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "django"
        verisons: ">=4.3"
