# Generated by Django 4.1.7 on 2023-02-27 03:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("etl", "0001_add_import_record"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importrecord",
            options={"verbose_name_plural": "Import Records"},
        ),
    ]
