---
- name: Install Ansible PostgreSQL dependencies
  ansible.builtin.apt:
    pkg:
    - libpq-dev
    - python3-psycopg2
    state: latest
  become: yes

- name: Create PostgreSQL database
  community.general.postgresql_db:
    name: "{{ postgresql_db_name }}"
  become: yes
  become_user: postgres

- name: Create PostgreSQL database user
  community.general.postgresql_user:
    db: "{{ postgresql_db_name }}"
    name: "{{ postgresql_user }}"
    password: "{{ postgresql_password }}"
    priv: ALL
    role_attr_flags: SUPERUSER,CREATEDB
    expires: infinity
  become: yes
  become_user: postgres

- name: Set PostgreSQL database owner
  community.general.postgresql_db:
    name: "{{ postgresql_db_name }}"
    owner: "{{ postgresql_password }}"
  become: yes
  become_user: postgres
...
