---
- name: Install snap core
  community.general.snap:
    name:
      - core
  become: yes

- name: Install certbot
  community.general.snap:
    name:
      - certbot
    classic: yes
  become: yes

- name: Create certbot symlink
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    owner: root
    group: root
    state: link
  become: yes

- name: Run certbot
  ansible.builtin.command: 
    argv:
      - "certbot"
      - "certonly"
      - "--nginx"
      - "--non-interactive"
      - "--keep"
      - "--agree-tos"
      - "--no-eff-email"
      - "-m {{ email_address }}"
      - "-d {{ web_domain }}"
    creates: "{{ certbot_key_dir }}/fullchain.pem"
  become: yes
...
