---
- name: "Add nodejs apt repo"
  ansible.builtin.deb822_repository:
    name: "nodesource_{{ nodejs_version }}"
    uris: "{{ nodejs_repo_url }}"
    types: deb
    architecture: amd64
    signed_by: "{{ nodejs_key_url }}"
    suites: nodistro
    components: main
    state: present
  become: yes

- name: "Install nodejs"
  ansible.builtin.apt:
    name: nodejs
    state: latest
    update_cache: yes
  become: yes

- name: "Update npm with npm"
  community.general.npm:
    global: yes
    name: npm
    state: latest
  become: yes

- name: "Install frontend dependencies"
  community.general.npm:
    path: "{{ project_source_dir }}"
    state: latest

- name: "Compile css from sass"
  ansible.builtin.command:
    argv:
      - npx
      - sass
      - -q
      - --style=compressed
      - --no-source-map
      - "{{ main_sass_path }}"
      - "{{ main_css_path }}"
    chdir: "{{ project_source_dir }}"
...
