# Generated by Django 4.0.2 on 2022-04-03 01:45

from django.db import migrations
from ..data import itunes


def insert_itunes_categories(apps, schema_editor):
    iTunesCategory = apps.get_model("podcasts", "iTunesCategory")
    categories = []
    for description, subcategory_description in itunes.categories:
        categories.append(
            iTunesCategory(
                description=description,
                subcategory_description=subcategory_description,
            )
        )
    iTunesCategory.objects.bulk_create(categories)


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_itunes_categories)
    ]
