# Generated by Django 4.0.2 on 2022-04-09 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_populate_itunes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastchapter',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapters', related_query_name='chapter', to='podcasts.podcastepisode'),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='episodes', related_query_name='episode', to='podcasts.podcast'),
        ),
    ]
