# Generated by Django 4.0.4 on 2022-05-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_add_podcasts_to_show_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastenclosure',
            name='url',
            field=models.URLField(),
        ),
    ]
