# Generated by Django 4.0.5 on 2022-06-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_add_custom_feed_url_and_episode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastchapter',
            name='image_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='podcastchapter',
            name='url_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
