# Generated by Django 4.1.1 on 2022-12-17 02:13

import frontrowcrew.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0006_add_chapter_url_image_descriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcastepisode",
            name="guid",
            field=models.CharField(
                blank=True, default=frontrowcrew.utils.uuid4_str, max_length=255
            ),
        ),
    ]
