# Generated by Django 4.2.6 on 2023-10-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0007_alter_podcastepisode_guid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="itunes_image_height",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="itunes_image_width",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
