# Generated by Django 4.2.6 on 2023-10-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0008_podcast_itunes_image_dimensions_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="description",
            field=models.TextField(blank=True, default="", max_length=4000),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="itunes_image",
            field=models.ImageField(
                blank=True,
                default="",
                height_field="itunes_image_height",
                upload_to="podcasts/podcast/itunes_image/",
                width_field="itunes_image_width",
            ),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="ttl",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
