# Generated by Django 4.1 on 2022-09-07 01:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
        ("shows", "0013_alter_content_options_alter_show_options_and_more"),
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                (
                    "catalog_number",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d+$",
                                message="Catalog number may only contain digits",
                            )
                        ],
                    ),
                ),
                ("pub_time", models.DateTimeField()),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=4000),
                ),
                ("body", models.TextField()),
                (
                    "author_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "author_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="",
                        height_field="image_height",
                        upload_to="creator/episode/image",
                        width_field="image_width",
                    ),
                ),
                ("image_description", models.TextField(blank=True, default="")),
                (
                    "image_height",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "image_width",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "itunes_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "itunes_image",
                    models.ImageField(
                        blank=True,
                        default="",
                        height_field="image_height",
                        upload_to="creator/episode/image",
                        width_field="image_width",
                    ),
                ),
                ("itunes_image_description", models.TextField(blank=True, default="")),
                (
                    "itunes_image_height",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "itunes_image_width",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "itunes_episode_number",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "itunes_season_number",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("itunes_explicit", models.BooleanField(default=None, null=True)),
                (
                    "itunes_episode_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Default"),
                            ("full", "Full"),
                            ("trailer", "Trailer"),
                            ("bonus", "Bonus"),
                        ],
                        default="",
                        max_length=255,
                    ),
                ),
                ("itunes_block", models.BooleanField(default=False)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="media.ftpdestination",
                    ),
                ),
                (
                    "mp3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="media.mp3"
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="shows.show"
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RelatedLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("url", models.URLField()),
                ("author", models.TextField()),
                ("description", models.TextField()),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="creator.episode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.PositiveIntegerField()),
                (
                    "end_time",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("url", models.URLField()),
                ("url_description", models.TextField()),
                ("image", models.ImageField(upload_to="")),
                ("image_description", models.TextField()),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="creator.episode",
                    ),
                ),
            ],
        ),
    ]
