# Generated by Django 4.2.7 on 2023-11-12 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("syndicators", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discord",
            fields=[
                (
                    "syndicator_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="syndicators.syndicator",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("webhook_url", models.URLField()),
                (
                    "server_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        default=None,
                        help_text="Option. Set this to enable automatic related link generation.",
                        null=True,
                    ),
                ),
                (
                    "thread_channel",
                    models.BooleanField(
                        default=False,
                        help_text="Set to true if the webhook is attached to a forum channel.",
                    ),
                ),
            ],
            bases=("syndicators.syndicator",),
        ),
    ]
