# Generated by Django 4.2.16 on 2024-11-23 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("syndicators", "0002_add_discord_syndicator"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bluesky",
            fields=[
                (
                    "syndicator_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="syndicators.syndicator",
                    ),
                ),
                ("username", models.TextField()),
                ("password", models.TextField()),
            ],
            bases=("syndicators.syndicator",),
        ),
    ]
