from django.urls import path, register_converter
from django.views.generic import base

from . import url_converters, views

register_converter(url_converters.FourDigitYearConverter, "yyyy")
register_converter(url_converters.TwoDigitMonthConverter, "mm")
register_converter(url_converters.TwoDigitDayConverter, "dd")

urlpatterns = [
    path(
        "episodes/",
        base.RedirectView.as_view(
            pattern_name="show-detail",
            permanent=True,
            query_string=True,
        ),
        {"show_slug": "geeknights"},
        name="legacy-episodes",
    ),
    path(
        "episodes/<yyyy:year>/",
        base.RedirectView.as_view(
            url="/geeknights/?year=%(year)s",
            permanent=True,
        ),
        name="legacy-redirect-episodes-year",
    ),
    path(
        "episodes/<yyyy:year>/<mm:month>/",
        base.RedirectView.as_view(
            url="/geeknights/?year=%(year)s&month=%(month)s",
            permanent=True,
        ),
        name="legacy-redirect-episodes-year-month",
    ),
    path(
        "episodes/<yyyy:year>/<mm:month>/<dd:day>/<slug:slug>/",
        views.geeknights_episode_detail_redirect,
        name="legacy-redirect-episodes-detail-date-slug",
    ),
    path(
        "episodes/<yyyy:year>/<mm:month>/<dd:day>/",
        views.geeknights_episode_detail_redirect,
        name="legacy-redirect-episodes-detail-date",
    ),
    path(
        "episodes/<str:category>/",
        views.geeknights_episode_list_redirect,
        name="legacy-redirect-episodes-category",
    ),
    path(
        "episodes/<str:category>/<yyyy:year>/",
        views.geeknights_episode_list_redirect,
        name="legacy-redirect-episodes-category-year",
    ),
    path(
        "episodes/<str:category>/<yyyy:year>/<mm:month>/",
        views.geeknights_episode_list_redirect,
        name="legacy-redirect-episodes-category-year-month",
    ),
    path(
        "index.php",
        base.RedirectView.as_view(
            pattern_name="homepage",
            permanent=True,
        ),
        name="legacy-redirect-php-homepage",
    ),
    path(
        "forum/",
        base.RedirectView.as_view(
            url="https://forum.frontrowcrew.com/",
            permanent=True,
            query_string=True,
        ),
        name="legacy-redirect-old-forum",
    ),
    path(
        "forum/<path:forumpath>",
        base.RedirectView.as_view(
            url="https://forum.frontrowcrew.com/%(forumpath)s",
            permanent=True,
            query_string=True,
        ),
        name="legacy-redirect-old-forum-deep",
    ),
    path(
        "archive/",
        base.RedirectView.as_view(
            pattern_name="show-list",
            permanent=True,
        ),
        name="legacy-redirect-archive",
    ),
    path(
        "bookclub/",
        base.RedirectView.as_view(
            pattern_name="show-detail",
            permanent=True,
            query_string=True,
        ),
        {
            "show_slug": "book-club",
        },
        name="legacy-redirect-bookclub",
    ),
    path(
        "bookclub/feed/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "book-club",
        },
        name="legacy-redirect-bookclub-feed",
    ),
    path(
        "bookclub/<catalog_number>/<slug:content_slug>/",
        base.RedirectView.as_view(
            pattern_name="content-detail",
            permanent=True,
        ),
        {
            "show_slug": "book-club",
        },
        name="legacy-redirect-bookclub-detail",
    ),
    path(
        "geeknights/monday/",
        base.RedirectView.as_view(
            pattern_name="show-detail",
            permanent=True,
            query_string=True,
        ),
        {"show_slug": "monday"},
        name="legacy-geeknights-show-monday",
    ),
    path(
        "geeknights/tuesday/",
        base.RedirectView.as_view(
            pattern_name="show-detail",
            permanent=True,
            query_string=True,
        ),
        {"show_slug": "tuesday"},
        name="legacy-geeknights-show-tuesday",
    ),
    path(
        "geeknights/wednesday/",
        base.RedirectView.as_view(
            pattern_name="show-detail",
            permanent=True,
            query_string=True,
        ),
        {"show_slug": "wednesday"},
        name="legacy-geeknights-show-wednesday",
    ),
    path(
        "geeknights/thursday/",
        base.RedirectView.as_view(
            pattern_name="show-detail",
            permanent=True,
            query_string=True,
        ),
        {"show_slug": "thursday"},
        name="legacy-geeknights-show-thursday",
    ),
    path(
        "geeknights/special/",
        base.RedirectView.as_view(
            pattern_name="show-detail",
            permanent=True,
            query_string=True,
        ),
        {"show_slug": "special"},
        name="legacy-geeknights-show-special",
    ),
    path(
        "geeknights/book-club/",
        base.RedirectView.as_view(
            pattern_name="show-detail",
            permanent=True,
            query_string=True,
        ),
        {"show_slug": "book-club"},
        name="legacy-geeknights-show-book-club",
    ),
    path(
        "geeknights/experimental/",
        base.RedirectView.as_view(
            pattern_name="show-detail",
            permanent=True,
            query_string=True,
        ),
        {"show_slug": "experimental"},
        name="legacy-geeknights-show-experimental",
    ),
    path(
        "geeknights/<yyyy:year>/",
        base.RedirectView.as_view(
            url="/geeknights/?year=%(year)s",
            permanent=True,
        ),
        name="legacy-redirect-geeknights-year",
    ),
    path(
        "geeknights/<yyyy:year>/<mm:month>/",
        base.RedirectView.as_view(
            url="/geeknights/?year=%(year)s&month=%(month)s",
            permanent=True,
        ),
        name="legacy-redirect-geeknights-year-month",
    ),
    path(
        "geeknights/feed/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "geeknights",
        },
        name="legacy-redirect-geeknights-feed",
    ),
    path(
        "geeknights/feed/total/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "geeknights",
        },
        name="legacy-redirect-geeknights-feed-total",
    ),
    path(
        "geeknights/feed/legacy/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "geeknights",
        },
        name="legacy-redirect-geeknights-feed-legacy",
    ),
    path(
        "geeknights/feed/monday/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "monday",
        },
        name="legacy-redirect-monday-feed",
    ),
    path(
        "geeknights/feed/tuesday/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "tuesday",
        },
        name="legacy-redirect-tuesday-feed",
    ),
    path(
        "geeknights/feed/wednesday/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "wednesday",
        },
        name="legacy-redirect-wednesday-feed",
    ),
    path(
        "geeknights/feed/thursday/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "thursday",
        },
        name="legacy-redirect-thursday-feed",
    ),
    path(
        "geeknights/feed/book-club/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "book-club",
        },
        name="legacy-redirect-book-club-feed",
    ),
    path(
        "geeknights/feed/experimental/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "experimental",
        },
        name="legacy-redirect-experimental-feed",
    ),
    path(
        "geeknights/feed/special/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "special",
        },
        name="legacy-redirect-special-feed",
    ),
    path(
        "news/<yyyy:year>/",
        base.RedirectView.as_view(
            url="/news/?year=%(year)s",
            permanent=True,
        ),
        name="legacy-redirect-news-year",
    ),
    path(
        "news/<yyyy:year>/<mm:month>/",
        base.RedirectView.as_view(
            url="/news/?year=%(year)s&month=%(month)s",
            permanent=True,
        ),
        name="legacy-redirect-news-year-month",
    ),
    path(
        "news/<yyyy:year>/<mm:month>/<dd:day>/<slug:slug>",
        views.news_detail_redirect,
        name="legacy-redirect-news-detail-date-slug",
    ),
    path(
        "news/feed/",
        base.RedirectView.as_view(
            pattern_name="show-rss",
            permanent=True,
        ),
        {
            "show_slug": "news",
        },
        name="legacy-redirect-news-feed",
    ),
    path(
        "things/feed/",
        base.RedirectView.as_view(
            pattern_name="totd-rss",
            permanent=True,
        ),
        name="legacy-redirect-totd-feed",
    ),
    path(
        "things/feed/legacy/",
        base.RedirectView.as_view(
            pattern_name="totd-rss",
            permanent=True,
        ),
        name="legacy-redirect-totd-feed-legacy",
    ),
    path(
        "videos/",
        base.RedirectView.as_view(
            pattern_name="show-list",
            permanent=True,
        ),
        name="legacy-redirect-videos",
    ),
    path(
        "videos/<slug:show_slug>/",
        base.RedirectView.as_view(
            pattern_name="show-detail",
            permanent=True,
            query_string=True,
        ),
        name="legacy-redirect-videos-show-list",
    ),
    path(
        "videos/<slug:show_slug>/<catalog_number>/<slug:content_slug>/",
        base.RedirectView.as_view(
            pattern_name="content-detail",
            permanent=True,
        ),
        name="legacy-redirect-videos-detail",
    ),
    path(
        "videos/tags/<str:tags>/",
        base.RedirectView.as_view(
            pattern_name="tag-filter",
            permanent=True,
            query_string=True,
        ),
        name="legacy-redirect-videos-tags",
    ),
    path(
        "feeds/news/",
        base.RedirectView.as_view(
            pattern_name="show-rss",
            permanent=True,
        ),
        {
            "show_slug": "news",
        },
        name="legacy-redirect-feed-news",
    ),
    path(
        "feeds/totd/",
        base.RedirectView.as_view(
            pattern_name="totd-rss",
            permanent=True,
        ),
        name="legacy-redirect-feed-totd",
    ),
    path(
        "feeds/all/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "geeknights",
        },
        name="legacy-redirect-feeds-geeknights",
    ),
    path(
        "feeds/monday/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "monday",
        },
        name="legacy-redirect-feeds-monday",
    ),
    path(
        "feeds/tuesday/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "tuesday",
        },
        name="legacy-redirect-feeds-tuesday",
    ),
    path(
        "feeds/wednesday/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "wednesday",
        },
        name="legacy-redirect-feeds-wednesday",
    ),
    path(
        "feeds/thursday/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "thursday",
        },
        name="legacy-redirect-feeds-thursday",
    ),
    path(
        "feeds/experimental/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "experimental",
        },
        name="legacy-redirect-feeds-experimental",
    ),
    path(
        "feeds/special/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "special",
        },
        name="legacy-redirect-feeds-special",
    ),
    path(
        "feeds/category/news/",
        base.RedirectView.as_view(
            pattern_name="show-rss",
            permanent=True,
        ),
        {
            "show_slug": "news",
        },
        name="legacy-redirect-feed-category-news",
    ),
    path(
        "feeds/category/totd/",
        base.RedirectView.as_view(
            pattern_name="totd-rss",
            permanent=True,
        ),
        name="legacy-redirect-feed-category/totd",
    ),
    path(
        "feeds/category/all/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "geeknights",
        },
        name="legacy-redirect-feeds-category/geeknights",
    ),
    path(
        "feeds/category/monday/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "monday",
        },
        name="legacy-redirect-feeds-category-monday",
    ),
    path(
        "feeds/category/tuesday/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "tuesday",
        },
        name="legacy-redirect-feeds-category/tuesday",
    ),
    path(
        "feeds/category/wednesday/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "wednesday",
        },
        name="legacy-redirect-feeds-category/wednesday",
    ),
    path(
        "feeds/category/thursday/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "thursday",
        },
        name="legacy-redirect-feeds-category-thursday",
    ),
    path(
        "feeds/category/experimental/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "experimental",
        },
        name="legacy-redirect-feeds-category-experimental",
    ),
    path(
        "feeds/category/special/",
        base.RedirectView.as_view(
            pattern_name="show-podcast-rss",
            permanent=True,
        ),
        {
            "show_slug": "special",
        },
        name="legacy-redirect-feeds-category-special",
    ),
    path(
        "<yyyy:year>/<mm:month>/<dd:day>/<slug:slug>",
        views.geeknights_episode_detail_redirect,
        name="legacy-redirect-episode-detail-date-slug",
    ),
    path(
        "<yyyy:year>/<mm:month>/<dd:day>/",
        views.geeknights_episode_detail_redirect,
        name="legacy-redirect-episode-detail-date",
    ),
    path(
        "<yyyy:year>/<mm:month>/<dd:day>/geeknights-<slug:slug>/",
        views.geeknights_episode_detail_redirect,
        name="legacy-redirect-episode-detail-date-geeknights-slug",
    ),
]
