# Generated by Django 3.2.9 on 2021-11-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('slug', models.SlugField()),
                ('logo', models.ImageField(upload_to='show/logos/')),
                ('thumbnail', models.ImageField(upload_to='show/thumbnails/')),
            ],
        ),
    ]
