# Generated by Django 4.0 on 2021-12-30 22:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('slug', models.SlugField(max_length=255)),
                ('image', models.ImageField(blank=True, default='', upload_to='content/images/')),
                ('catalog_number', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^\\d+$', message='Catalog number may only contain digits')])),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('pub_time', models.DateTimeField()),
                ('published', models.BooleanField(default=False)),
                ('rendered_html', models.TextField(blank=True)),
                ('original_content', models.TextField(blank=True, default='')),
                ('content_format', models.CharField(choices=[('HTML', 'HTML'), ('MD', 'Markdown')], default='MD', max_length=4)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shows.show')),
            ],
            options={
                'ordering': ['-pub_time'],
                'unique_together': {('show', 'catalog_number')},
            },
        ),
    ]
