# Generated by Django 4.0.2 on 2022-04-12 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_add_podcasts_to_show_models'),
        ('shows', '0004_show_display_in_nav'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-pub_time'], 'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
        migrations.AlterModelOptions(
            name='show',
            options={'verbose_name': 'Show', 'verbose_name_plural': 'Shows'},
        ),
        migrations.RemoveField(
            model_name='content',
            name='image',
        ),
        migrations.AddField(
            model_name='content',
            name='podcast_episode',
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='podcasts.podcastepisode'
            ),
        ),
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='show',
            name='logo_height',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='logo_width',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='podcast',
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='podcasts.podcast'
            ),
        ),
        migrations.AddField(
            model_name='show',
            name='thumbnail_height',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='thumbnail_width',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='logo',
            field=models.ImageField(
                blank=True,
                default='',
                height_field='logo_height',
                upload_to='shows/logo/',
                width_field='logo_width'
            ),
        ),
        migrations.AlterField(
            model_name='show',
            name='thumbnail',
            field=models.ImageField(
                blank=True,
                default='',
                height_field='thumbnail_height',
                upload_to='shows/thumbnail/',
                width_field='thumbnail_width'
            ),
        ),
    ]
