# Generated by Django 4.0.2 on 2022-04-15 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_add_podcasts_to_show_models'),
        ('shows', '0005_add_podcasts_to_content_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='sub_shows',
            field=models.ManyToManyField(blank=True, to='shows.Show'),
        ),
    ]
