# Generated by Django 4.0.2 on 2022-04-15 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_add_podcasts_to_show_models'),
        ('shows', '0006_add_sub_show_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='podcast_episode',
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='podcasts.podcastepisode'
            ),
        ),
        migrations.AlterField(
            model_name='show',
            name='podcast',
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='podcasts.podcast'
            ),
        ),
    ]
