# Generated by Django 4.0.4 on 2022-05-03 01:24

from django.db import migrations
from shows import models


def create_thing_of_the_day_type(apps, schema_editor):
    RelatedLinkType = apps.get_model("shows", "RelatedLinkType")
    RelatedLinkType.objects.create(
        id=models.RelatedLinkType.THING_OF_THE_DAY,
        description="Thing of the Day"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0008_add_related_link'),
    ]

    operations = [
        migrations.RunSQL(
            sql="TRUNCATE TABLE shows_relatedlinktype, shows_relatedlink;",
            reverse_sql="TRUNCATE TABLE shows_relatedlinktype, shows_relatedlink;",
        ),
        migrations.RunPython(
            create_thing_of_the_day_type,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunSQL(
            sql=[
                (
                    "ALTER sequence shows_relatedlinktype_id_seq RESTART WITH %s;",
                    [models.RelatedLinkType.THING_OF_THE_DAY + 1],
                ),
            ],
            reverse_sql=[
                (
                    "ALTER sequence shows_relatedlinktype_id_seq RESTART WITH %s;",
                    [models.RelatedLinkType.THING_OF_THE_DAY],
                ),
            ]
        )
    ]
