# Generated by Django 4.0.4 on 2022-05-08 19:23

from django.contrib.postgres import search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0010_add_tags_to_content'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE shows_content
            ADD COLUMN search_vector tsvector
            GENERATED ALWAYS AS (
                setweight(to_tsvector('english', title), 'A') ||
                setweight(to_tsvector('english', rendered_html), 'B')
            ) STORED;
            """,
            state_operations=[
                migrations.AddField(
                    model_name='content',
                    name='search_vector',
                    field=search.SearchVectorField(editable=False),
                ),
            ]
        )
    ]
