# Generated by Django 4.0.4 on 2022-05-08 19:34

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0011_add_content_search_vector'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='content',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['search_vector'],
                name='shows_conte_search__d513bd_gin'
            ),
        ),
    ]
