# Generated by Django 4.0.5 on 2022-06-14 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0012_add_search_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'get_latest_by': 'pub_time', 'ordering': ['-pub_time'], 'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
        migrations.AlterModelOptions(
            name='show',
            options={'get_latest_by': 'pub_time', 'verbose_name': 'Show', 'verbose_name_plural': 'Shows'},
        ),
        migrations.AlterField(
            model_name='relatedlink',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_links', to='shows.content'),
        ),
    ]
