# Generated by Django 4.1.1 on 2022-11-07 01:07

from django.db import migrations
from django.utils.translation import gettext_lazy as _

from shows import models


def create_forum_thread_type(apps, schema_editor):
    RelatedLinkType = apps.get_model("shows", "RelatedLinkType")
    RelatedLinkType.objects.create(
        id=models.RelatedLinkType.FORUM_THREAD,
        description=_("Forum Thread"),
    )


def delete_forum_thread_type(apps, schema_editor):
    RelatedLinkType = apps.get_model("shows", "RelatedLinkType")
    RelatedLinkType.objects.filter(
        id=models.RelatedLinkType.FORUM_THREAD,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0013_alter_content_options_alter_show_options_and_more"),
    ]

    operations = [
        migrations.RunPython(
            create_forum_thread_type,
            delete_forum_thread_type,
        ),
        migrations.RunSQL(
            sql=[
                (
                    "ALTER sequence shows_relatedlinktype_id_seq RESTART WITH %s;",
                    [models.RelatedLinkType.FORUM_THREAD + 1],
                ),
            ],
            reverse_sql=[
                (
                    "ALTER sequence shows_relatedlinktype_id_seq RESTART WITH %s;",
                    [models.RelatedLinkType.FORUM_THREAD],
                ),
            ]
        )
    ]
