# Generated by Django 4.1.1 on 2022-12-17 00:33

from django.db import migrations
from django.utils.translation import gettext_lazy as _

from shows import models


def create_related_link_types(apps, schema_editor):
    RelatedLinkType = apps.get_model("shows", "RelatedLinkType")
    RelatedLinkType.objects.create(
        id=models.RelatedLinkType.YOUTUBE_VIDEO,
        description=_("YouTube Video"),
    )
    RelatedLinkType.objects.create(
        id=models.RelatedLinkType.PURCHASE_LINK,
        description=_("Purchase Link"),
    )


def delete_related_link_types(apps, schema_editor):
    RelatedLinkType = apps.get_model("shows", "RelatedLinkType")
    RelatedLinkType.objects.filter(
        id=models.RelatedLinkType.YOUTUBE_VIDEO,
    ).delete()
    RelatedLinkType.objects.filter(
        id=models.RelatedLinkType.PURCHASE_LINK,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0014_create_forum_thread_type"),
    ]

    operations = [
        migrations.RunPython(
            create_related_link_types,
            delete_related_link_types,
        ),
        migrations.RunSQL(
            sql=[
                (
                    "ALTER sequence shows_relatedlinktype_id_seq RESTART with %s;",
                    [models.RelatedLinkType.PURCHASE_LINK + 1]
                ),
            ],
            reverse_sql=[
                (
                    "ALTER sequence shows_relatedlinktype_id_seq RESTART with %s;",
                    [models.RelatedLinkType.YOUTUBE_VIDEO]
                )
            ]
        )
    ]
