# Generated by Django 4.1.1 on 2022-12-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0015_add_more_related_link_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="image",
            field=models.ImageField(
                blank=True,
                default="",
                height_field="image_height",
                upload_to="shows/content/image/",
                width_field="image_width",
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="image_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="content",
            name="image_height",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="content",
            name="image_width",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
