# Generated by Django 4.1.1 on 2022-12-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0017_add_content_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="related_content",
            field=models.ManyToManyField(to="shows.content"),
        ),
    ]
