# Generated by Django 4.1.5 on 2023-02-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embeds", "0001_initial"),
        ("shows", "0022_remove_defaults_from_type_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="embedded_media",
            field=models.ManyToManyField(to="embeds.media"),
        ),
    ]
