# Generated by Django 4.1.7 on 2023-02-28 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shows", "0025_alter_content_options_alter_relatedlinktype_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="parent_show",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child_shows",
                to="shows.show",
            ),
        ),
    ]
