# Generated by Django 4.1.7 on 2023-02-28 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shows", "0028_remove_sub_shows_relation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="parent_show",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child_shows",
                to="shows.show",
            ),
        ),
    ]
