# Generated by Django 4.2.5 on 2023-10-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shows", "0029_alter_show_parent_show"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="priority",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
