# Generated by Django 4.2.6 on 2023-10-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shows", "0030_add_priority_to_show"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatedlink",
            name="author",
            field=models.TextField(blank=True, default=""),
        ),
    ]
