# Generated by Django 4.2.6 on 2023-10-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shows", "0031_related_link_author_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="rendered_related_links",
            field=models.TextField(blank=True, default=""),
        ),
    ]
