# Generated by Django 4.2.7 on 2023-11-12 01:59

from django.db import migrations
from django.utils.translation import gettext_lazy as _

from shows import models


def create_related_link_types(apps, schema_editor):
    RelatedLinkType = apps.get_model("shows", "RelatedLinkType")
    RelatedLinkType.objects.create(
        id=models.RelatedLinkType.DISCORD_CHAT,
        description=_("Discord Chat"),
        plural_description=_("Discord Chats"),
        slug="discord_chat",
        plural_slug="discord_chats",
    )


def delete_related_link_types(apps, schema_editor):
    RelatedLinkType = apps.get_model("shows", "RelatedLinkType")
    RelatedLinkType.objects.filter(
        id=models.RelatedLinkType.DISCORD_CHAT,
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("shows", "0032_add_rendered_related_links"),
    ]

    operations = [
        migrations.RunPython(
            create_related_link_types,
            delete_related_link_types,
        ),
        migrations.RunSQL(
            sql=[
                (
                    "ALTER sequence shows_relatedlinktype_id_seq RESTART with %s;",
                    [models.RelatedLinkType.DISCORD_CHAT + 1],
                ),
            ],
            reverse_sql=[
                (
                    "ALTER sequence shows_relatedlinktype_id_seq RESTART with %s;",
                    [models.RelatedLinkType.DISCORD_CHAT],
                )
            ],
        ),
    ]
