# Generated by Django 4.1 on 2022-09-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FTPDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("host", models.TextField()),
                ("username", models.TextField(blank=True, default="")),
                ("password", models.TextField(blank=True, default="")),
                ("directory", models.TextField(blank=True, default="")),
                (
                    "custom_timeout",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "url_prefix",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The URL at which the file will be available after uploading.",
                    ),
                ),
            ],
            options={
                "verbose_name": "FTP Destination",
                "verbose_name_plural": "FTP Destinations",
            },
        ),
        migrations.CreateModel(
            name="MP3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(upload_to="MP3/")),
            ],
            options={
                "verbose_name": "MP3",
                "verbose_name_plural": "MP3s",
                "get_latest_by": ["-upload_time"],
            },
        ),
    ]
