# Generated by Django 4.1.7 on 2023-02-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ftpdestination",
            name="url_prefix",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The URL at which the file will be available after uploading.",
                verbose_name="URL Prefix",
            ),
        ),
    ]
