---
- name: Set python environment variables
  ansible.builtin.set_fact:
    env_vars: "{{ env_vars|default({}) | combine( { project_name | upper + '_' + item.key | upper: item.value } ) }}"
  loop: "{{ python_environment.vars | dict2items }}"
  no_log: True
...
