---
- name: Add deadsnakes ppa
  ansible.builtin.apt_repository:
    repo: 'ppa:deadsnakes/ppa'
  become: yes

- name: Install Python3 packages
  ansible.builtin.apt:
    pkg:
    - python3
    - python3-dev
    - python3-distutils
    - python3-testresources
    - python3-pip
    - python3-setuptools
    - python3-tk
    - python3-venv
    - python-is-python3
    - "python{{ python_version }}"
    - "python{{ python_version }}-dev"
    - "python{{ python_version }}-distutils"
    - "python{{ python-version }}-venv"
    - "python{{ python-version }}-tk"
    state: latest
  become: yes

- name: Install system dependencies for Python modules
  ansible.builtin.apt:
    pkg:
    - build-essential
    - libexempi8
    - libfreetype6-dev
    - libjpeg-dev
    - liblcms2-dev
    - libmemcached-dev
    - libpq-dev
    - libtiff-dev
    - libwebp-dev
    - openssl
    - tcl-dev
    - tk-dev
    - zlib1g-dev
    state: latest
  become: yes

- name: Ensure pip is installed
  command: "python{{ python_version }} -m ensurepip --upgrade"
  become: yes

- name: Upgrade pip using pip
  ansible.builtin.pip:
    executable: "pip{{ python_version }}"
    name: pip
    state: latest
  become: yes

- name: Install testresources
  ansible.builtin.pip:
    executable: "pip{{ python_version }}"
    name: testresources
    state: latest
  become: yes

- name: Install virtualenv
  ansible.builtin.pip:
    executable: "pip{{ python_version }}"
    name: virtualenv
    state: latest
  become: yes

- name: Install poetry
  ansible.builtin.pip:
    executable: "pip{{ python_version }}"
    name: "poetry~={{ poetry_version }}"

- name: Set poetry bin and requirements.txt paths
  ansible.builtin.set_fact:
    poetry_bin: "{{ ansible_env.HOME }}/.local/bin/poetry"
    requirements_file: "{{ project_source_dir }}/requirements.txt"

- name: Generate requirements.txt
  ansible.builtin.command:
    chdir: "{{ project_source_dir }}"
    cmd: "{{ poetry_bin }} export --output {{ requirements_file }}"

- name: Check if virtualenv has correct Python version
  stat:
    path: "{{ virtualenv_bin_dir }}/python{{ python_version }}"
  register: virtualenv_data

- name: Delete virtualenv if its Python version is old
  file:
    state: absent
    path: "{{ virtualenv_project_dir }}"
  when: not virtualenv_data.exists

- name: Install project Python requirements
  ansible.builtin.pip:
    executable: "pip{{ python_version }}"
    requirements: "{{ requirements_file }}"
    virtualenv: "{{ virtualenv_project_dir }}"
    virtualenv_python: "python{{ python_version }}"
  notify: "restart web application server"

- name: Remove requirements.txt
  ansible.builtin.file:
    path: "{{ requirements_file }}"
    state: absent
...
