---
- name: Checkout code
  ansible.builtin.git:
    repo: "{{ git_repo }}"
    dest: "{{ project_source_dir }}"
    version: "{{ git_version }}"
    key_file: "{{ deploy_key_path }}"
    accept_hostkey: yes
    force: yes
    update: yes
    refspec: "+refs/heads/*:refs/remotes/origin/*"
    umask: '0022'
...
