name: Django Tests

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      FRONTROWCREW_DEBUG: False
      FRONTROWCREW_DB_NAME: test
      FRONTROWCREW_DB_USER: test
      FRONTROWCREW_DB_PASSWORD: test
      FRONTROWCREW_DB_HOST: 127.0.0.1
      FRONTROWCREW_DB_PORT: 5432
      FRONTROWCREW_CELERY_USER: test
      FRONTROWCREW_CELERY_PASSWORD: test
      FRONTROWCREW_CELERY_HOST: 127.0.0.1
      FRONTROWCREW_CELERY_VHOST: test

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.FRONTROWCREW_DB_USER }}
          POSTGRES_PASSWORD: ${{ env.FRONTROWCREW_DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      rabbitmq:
        image: rabbitmq:latest
        env:
          RABBITMQ_DEFAULT_USER: ${{ env.FRONTROWCREW_CELERY_USER }}
          RABBITMQ_DEFAULT_PASSWORD: ${{ env.FRONTROWCREW_CELERY_PASSWORD }}
          RABBITMQ_DEFAULT_VHOST: ${{ env.FRONTROWCREW_CELERY_VHOST }}
        ports:
          - 5672:5672
        options: >-
          --health-cmd "rabbitmqctl node_health_check"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install libexempi8
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Compile SASS to CSS
        uses: gha-utilities/sass-build@v0.5.1
        with:
          source: assets/sass/main.scss
          destination: static/css/main.css
      - name: Install poetry
        run: pipx install poetry
      - name: Install Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry install
      - name: Check for Django Migrations
        run: |
          poetry run python manage.py makemigrations --check --dry-run
      - name: Run Django tests
        run: |
          poetry run python manage.py test --shuffle --parallel auto
      - name: Verify collectstatic is working
        run: |
          poetry run python manage.py collectstatic -v3 --noinput