name: Django Tests

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      BETAFRONTROWCREW_DEBUG: False
      BETAFRONTROWCREW_DB_NAME: test
      BETAFRONTROWCREW_DB_USER: test
      BETAFRONTROWCREW_DB_PASSWORD: test
      BETAFRONTROWCREW_DB_HOST: 127.0.0.1
      BETAFRONTROWCREW_DB_PORT: 5432
      BETAFRONTROWCREW_MEMCACHED_SOCKET: 127.0.0.1:11211
      BETAFRONTROWCREW_CELERY_USER: test
      BETAFRONTROWCREW_CELERY_PASSWORD: test
      BETAFRONTROWCREW_CELERY_HOST: 127.0.0.1
      BETAFRONTROWCREW_CELERY_VHOST: test

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.BETAFRONTROWCREW_DB_USER }}
          POSTGRES_PASSWORD: ${{ env.BETAFRONTROWCREW_DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      memcached:
        image: memcached:latest
        ports:
          - 11211:11211
        options: >-
          --health-cmd "timeout 5 bash -c 'cat < /dev/null > /dev/udp/127.0.0.1/11211'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      rabbitmq:
        image: rabbitmq:latest
        env:
          RABBITMQ_DEFAULT_USER: ${{ env.BETAFRONTROWCREW_CELERY_USER }}
          RABBITMQ_DEFAULT_PASSWORD: ${{ env.BETAFRONTROWCREW_CELERY_PASSWORD }}
          RABBITMQ_DEFAULT_VHOST: ${{ env.BETAFRONTROWCREW_CELERY_VHOST }}
        ports:
          - 5672:5672
        options: >-
          --health-cmd "rabbitmqctl node_health_check"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install libmemcached-dev libexempi8
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Install Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry install
      # Add this for tracebacks
      - run: poetry add tblib
      - name: Check for Django Migrations
        run: |
          poetry run python manage.py makemigrations --check --dry-run
      - name: Run Django tests
        run: |
          poetry run python manage.py test --shuffle --parallel auto
